### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by SokichiFujita** [strapi/strapi-starter-gatsby-catalog#22]
When I just execute the installation command, following error is displayed. Are there any pre-requirements or something?

```
➜ node -v
v16.13.1
```

```
➜  npx create-strapi-starter my-project gatsby-catalog
? Choose your installation type Quickstart (recommended)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getPackageInfo (/Users/s/.npm/_npx/ecd569b0a81a6814/node_modules/create-strapi-starter/utils/fetch-npm-starter.js:19:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getStarterInfo (/Users/s/.npm/_npx/ecd569b0a81a6814/node_modules/create-strapi-starter/utils/build-starter.js:109:26)
    at async buildStarter (/Users/s/.npm/_npx/ecd569b0a81a6814/node_modules/create-strapi-starter/utils/build-starter.js:133:7)

```

**Comment by SokichiFujita** [comment]
```
npx create-strapi-starter@3 my-project gatsby-catalog
```

will solve this issue. I feel the documentation or template should be updated.

**Comment by candentmind** [comment]
https://github.com/strapi/strapi-starter-gatsby-catalog/issues/22#issuecomment-989021539
oh yeah, indeed, using version3 did work perfectly.. thanks ^^
